### ISSUE TITLE
USER STORY: About page

### ISSUE THREAD

**Issue by Noah-Samawi** [Noah-Samawi/pp5-wander-wise-frontend#10]
**As a user**, I can view the About page so that I can gain information about Wander Wise.

## Acceptance Criteria:
- **Acceptance Criteria 1**: There should be a visible link in the navbar to the About page.
- **Acceptance Criteria 2**: The About page should provide a brief description of Wander Wise .

## Tasks:
- [x] Create the About page component.
- [x] Add the content to the About page.
- [x] Add the About page component to the routes in `app.js`.
- [x] Add the About page link to the navbar.
