### ISSUE TITLE
USER STORY: Testing

### ISSUE THREAD

**Issue by Noah-Samawi** [Noah-Samawi/pp5-wander-wise-frontend#23]
As a Project Owner, I can conduct thorough testing so that the application is robust, error-free, and provides a smooth user experience.

## Acceptance Criteria:
- **Acceptance Criteria 1:** All tests should be free of errors in all parts of the application, other than those errors inherent to the framework or libraries being used.
- **Acceptance Criteria 2:**
- **Acceptance Criteria 3:** The application should pass performance testing, demonstrating efficient loading and operation, and optimally utilizing resources.
- **Acceptance Criteria 4:** The application must exhibit compatibility across multiple browsers, ensuring that users on different platforms have a consistent experience.
- **Acceptance Criteria 5:** Automated tests must cover some functionalities of the application, and all tests should pass.
- **Acceptance Criteria 6:** Manual testing should be conducted, specifically focusing on edge cases and non-typical user flows, to ensure overall quality of the application.

## Tasks:
- [x] Validate HTML
- [x] Validate CSS
- [ ] Validate JavaScript (JSX)
- [ ] Do Performance test
- [x] Check Browser compatibility
- [x] Automated testing
- [x] Manual testing
- [x] Testing all backend
