### ISSUE TITLE
USER STORY: Location

### ISSUE THREAD

**Issue by Noah-Samawi** [Noah-Samawi/pp5-wander-wise-frontend#25]
As a user I can see a posts location so that I can know where the memory was made

## Acceptance Criteria:
- **Acceptance Criteria 1:** Post app is updated with model for location
- **Acceptance Criteria 2:** Location is visible on every post.

## Tasks
- [x] Create a location model with a Foreign Key relationship to the post model
- [ ] Create a migration for the changes
- [ ] Update database schema
- [ ] Update the post view to show location
