### ISSUE TITLE
USER STORY: Popular wanderers

### ISSUE THREAD

**Issue by Noah-Samawi** [Noah-Samawi/pp5-wander-wise-frontend#31]
As a user I can see which the most popular wanderers are so that I can get inspired by them

## Acceptance Cirteria:
- Acceptance Criteria 1: The most popular wanderers are presented in a visually appealing and clear manner.
- Acceptance Criteria 2: I can click on a wanderers to access more information about the person and view their content.
## Tasks
- [x] Create a functionality to retrieve and display information about the wanderers, including their profiles and content.
- [x] Design and implement a visually pleasing layout to showcase the most popular wanderers.
- [x] Implement a feature that allows users to click on a wanderer to view more detailed information and explore their content.
- [x] Add a button to quickly follow the popular user.
